# -*- mode: ruby -*-
# vi: set ft=ruby :
#
Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"

  config.vm.define "client" do |client|
    client.vm.hostname = "wg-client"
    client.vm.network "private_network", ip: "192.168.99.22"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true
    vb.memory = 2048
  end

  config.vm.provision "shell", inline: "yum -y update 2>&1 > /dev/null"
  config.vm.provision :reload
  config.vm.provision "shell", inline: <<-SHELL
    yum -y install epel-release
    yum -y config-manager --set-enabled PowerTools
    yum -y copr enable jdoss/wireguard
    yum -y install wireguard-dkms wireguard-tools
  SHELL

end
