# -*- mode: ruby -*-
# vi: set ft=ruby :
#
Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"

  config.vm.hostname = "elastic"
  config.vm.network "private_network", ip: "192.168.99.77"

  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true
    vb.memory = 2048
  end
  config.vm.provision "shell", path: "deploy.sh"
end
