# -*- mode: ruby -*-
# vi: set ft=ruby :

# Semyon Vasilkov (job@zimmnik.ru)
 
Vagrant.configure("2") do |config|
  config.vm.box = "fedora/36-cloud-base"

  config.vm.provider :libvirt do |lv|
    lv.qemu_use_session = false
    lv.cpus = 2
    lv.memory = 2048
    lv.video_type = 'none'
    lv.graphics_type = 'none'
    lv.storage :file, :size => '2G'
  end

  config.vm.define "node1" do |node1|
    config.vm.hostname = 'node1'
  end
 
  config.vm.define "node2" do |node2|
    config.vm.hostname = 'node2'
  end
 
  config.vm.provision "shell", path: "run.sh"
end

#vagrant destroy -f && time vagrant up --color --no-destroy-on-error
